### ISSUE TITLE
workflow na githubie

### ISSUE THREAD

**Issue by wejengin2** [wejengin2/procscape#4]
Workflow na githubie ma jakis problem z comat::it_metric i wychodzi czerwony, lokalnie działa.
https://github.com/wejengin2/procscape/runs/4845667902?check_suite_focus=true

**Comment by Nowosad** [comment]
Jest tak dlatego, że nowej wersji comat nie ma jeszcze na CRAN. Tymczasowo można dodać w GitHub action, żeby instalowało comat z GitHuba...

**Comment by wejengin2** [comment]
No tak, myślałem o tym ale nie do końca sprawdziłem. Dziękuję
